package dev.fudgeu.pquery.parser

enum class Token {
    BOOLEAN_RESOLVABLE,
    NUMBER_RESOLVABLE,
    STRING_RESOLVABLE,
    LOGICAL_OPERATOR,
    COMPARISON_OPERATOR,
    MATH_OPERATOR,
    LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS,
    LEFT_SQUARE_BRACKET,
    RIGHT_SQUARE_BRACKET,
    STRING_LIST_RESOLVABLE,
    NUMBER_LIST_RESOLVABLE,
    COMMA,
    CONDITIONAL_CHAIN,
}